-- Migration: Convert country names to ISO 3166-1 alpha-2 codes
-- This migration converts all existing full country names to ISO 2-letter codes

-- Update tenant_references current_country field
UPDATE tenant_references
SET current_country = CASE current_country
  WHEN 'United Kingdom' THEN 'GB'
  WHEN 'United States' THEN 'US'
  WHEN 'Ireland' THEN 'IE'
  WHEN 'Canada' THEN 'CA'
  WHEN 'Australia' THEN 'AU'
  WHEN 'Germany' THEN 'DE'
  WHEN 'France' THEN 'FR'
  WHEN 'Spain' THEN 'ES'
  WHEN 'Italy' THEN 'IT'
  WHEN 'Netherlands' THEN 'NL'
  WHEN 'Belgium' THEN 'BE'
  WHEN 'Switzerland' THEN 'CH'
  WHEN 'Austria' THEN 'AT'
  WHEN 'Sweden' THEN 'SE'
  WHEN 'Norway' THEN 'NO'
  WHEN 'Denmark' THEN 'DK'
  WHEN 'Finland' THEN 'FI'
  WHEN 'Poland' THEN 'PL'
  WHEN 'India' THEN 'IN'
  WHEN 'China' THEN 'CN'
  WHEN 'Japan' THEN 'JP'
  WHEN 'Singapore' THEN 'SG'
  WHEN 'South Korea' THEN 'KR'
  WHEN 'Brazil' THEN 'BR'
  WHEN 'Mexico' THEN 'MX'
  WHEN 'Argentina' THEN 'AR'
  WHEN 'South Africa' THEN 'ZA'
  WHEN 'New Zealand' THEN 'NZ'
  WHEN 'Afghanistan' THEN 'AF'
  WHEN 'Albania' THEN 'AL'
  WHEN 'Algeria' THEN 'DZ'
  WHEN 'Andorra' THEN 'AD'
  WHEN 'Angola' THEN 'AO'
  WHEN 'Armenia' THEN 'AM'
  WHEN 'Azerbaijan' THEN 'AZ'
  WHEN 'Bahrain' THEN 'BH'
  WHEN 'Bangladesh' THEN 'BD'
  WHEN 'Belarus' THEN 'BY'
  WHEN 'Belize' THEN 'BZ'
  WHEN 'Benin' THEN 'BJ'
  WHEN 'Bhutan' THEN 'BT'
  WHEN 'Bolivia' THEN 'BO'
  WHEN 'Bosnia and Herzegovina' THEN 'BA'
  WHEN 'Botswana' THEN 'BW'
  WHEN 'Brunei' THEN 'BN'
  WHEN 'Bulgaria' THEN 'BG'
  WHEN 'Burkina Faso' THEN 'BF'
  WHEN 'Burundi' THEN 'BI'
  WHEN 'Cambodia' THEN 'KH'
  WHEN 'Cameroon' THEN 'CM'
  WHEN 'Cape Verde' THEN 'CV'
  WHEN 'Central African Republic' THEN 'CF'
  WHEN 'Chad' THEN 'TD'
  WHEN 'Chile' THEN 'CL'
  WHEN 'Colombia' THEN 'CO'
  WHEN 'Comoros' THEN 'KM'
  WHEN 'Congo' THEN 'CG'
  WHEN 'Costa Rica' THEN 'CR'
  WHEN 'Croatia' THEN 'HR'
  WHEN 'Cuba' THEN 'CU'
  WHEN 'Cyprus' THEN 'CY'
  WHEN 'Czech Republic' THEN 'CZ'
  WHEN 'Djibouti' THEN 'DJ'
  WHEN 'Dominican Republic' THEN 'DO'
  WHEN 'Ecuador' THEN 'EC'
  WHEN 'Egypt' THEN 'EG'
  WHEN 'El Salvador' THEN 'SV'
  WHEN 'Equatorial Guinea' THEN 'GQ'
  WHEN 'Eritrea' THEN 'ER'
  WHEN 'Estonia' THEN 'EE'
  WHEN 'Ethiopia' THEN 'ET'
  WHEN 'Fiji' THEN 'FJ'
  WHEN 'Gabon' THEN 'GA'
  WHEN 'Gambia' THEN 'GM'
  WHEN 'Georgia' THEN 'GE'
  WHEN 'Ghana' THEN 'GH'
  WHEN 'Greece' THEN 'GR'
  WHEN 'Guatemala' THEN 'GT'
  WHEN 'Guinea' THEN 'GN'
  WHEN 'Guinea-Bissau' THEN 'GW'
  WHEN 'Guyana' THEN 'GY'
  WHEN 'Haiti' THEN 'HT'
  WHEN 'Honduras' THEN 'HN'
  WHEN 'Hungary' THEN 'HU'
  WHEN 'Iceland' THEN 'IS'
  WHEN 'Indonesia' THEN 'ID'
  WHEN 'Iran' THEN 'IR'
  WHEN 'Iraq' THEN 'IQ'
  WHEN 'Israel' THEN 'IL'
  WHEN 'Jamaica' THEN 'JM'
  WHEN 'Jordan' THEN 'JO'
  WHEN 'Kazakhstan' THEN 'KZ'
  WHEN 'Kenya' THEN 'KE'
  WHEN 'Kiribati' THEN 'KI'
  WHEN 'Kuwait' THEN 'KW'
  WHEN 'Kyrgyzstan' THEN 'KG'
  WHEN 'Laos' THEN 'LA'
  WHEN 'Latvia' THEN 'LV'
  WHEN 'Lebanon' THEN 'LB'
  WHEN 'Lesotho' THEN 'LS'
  WHEN 'Liberia' THEN 'LR'
  WHEN 'Libya' THEN 'LY'
  WHEN 'Liechtenstein' THEN 'LI'
  WHEN 'Lithuania' THEN 'LT'
  WHEN 'Luxembourg' THEN 'LU'
  WHEN 'Macedonia' THEN 'MK'
  WHEN 'Madagascar' THEN 'MG'
  WHEN 'Malawi' THEN 'MW'
  WHEN 'Malaysia' THEN 'MY'
  WHEN 'Maldives' THEN 'MV'
  WHEN 'Mali' THEN 'ML'
  WHEN 'Malta' THEN 'MT'
  WHEN 'Marshall Islands' THEN 'MH'
  WHEN 'Mauritania' THEN 'MR'
  WHEN 'Mauritius' THEN 'MU'
  WHEN 'Micronesia' THEN 'FM'
  WHEN 'Moldova' THEN 'MD'
  WHEN 'Monaco' THEN 'MC'
  WHEN 'Mongolia' THEN 'MN'
  WHEN 'Montenegro' THEN 'ME'
  WHEN 'Morocco' THEN 'MA'
  WHEN 'Mozambique' THEN 'MZ'
  WHEN 'Myanmar' THEN 'MM'
  WHEN 'Namibia' THEN 'NA'
  WHEN 'Nauru' THEN 'NR'
  WHEN 'Nepal' THEN 'NP'
  WHEN 'Nicaragua' THEN 'NI'
  WHEN 'Niger' THEN 'NE'
  WHEN 'Nigeria' THEN 'NG'
  WHEN 'North Korea' THEN 'KP'
  WHEN 'Oman' THEN 'OM'
  WHEN 'Pakistan' THEN 'PK'
  WHEN 'Palau' THEN 'PW'
  WHEN 'Panama' THEN 'PA'
  WHEN 'Papua New Guinea' THEN 'PG'
  WHEN 'Paraguay' THEN 'PY'
  WHEN 'Peru' THEN 'PE'
  WHEN 'Philippines' THEN 'PH'
  WHEN 'Portugal' THEN 'PT'
  WHEN 'Qatar' THEN 'QA'
  WHEN 'Romania' THEN 'RO'
  WHEN 'Russia' THEN 'RU'
  WHEN 'Rwanda' THEN 'RW'
  WHEN 'Saint Kitts and Nevis' THEN 'KN'
  WHEN 'Saint Lucia' THEN 'LC'
  WHEN 'Saint Vincent and the Grenadines' THEN 'VC'
  WHEN 'Samoa' THEN 'WS'
  WHEN 'San Marino' THEN 'SM'
  WHEN 'Sao Tome and Principe' THEN 'ST'
  WHEN 'Saudi Arabia' THEN 'SA'
  WHEN 'Senegal' THEN 'SN'
  WHEN 'Serbia' THEN 'RS'
  WHEN 'Seychelles' THEN 'SC'
  WHEN 'Sierra Leone' THEN 'SL'
  WHEN 'Slovakia' THEN 'SK'
  WHEN 'Slovenia' THEN 'SI'
  WHEN 'Solomon Islands' THEN 'SB'
  WHEN 'Somalia' THEN 'SO'
  WHEN 'South Sudan' THEN 'SS'
  WHEN 'Sri Lanka' THEN 'LK'
  WHEN 'Sudan' THEN 'SD'
  WHEN 'Suriname' THEN 'SR'
  WHEN 'Swaziland' THEN 'SZ'
  WHEN 'Syria' THEN 'SY'
  WHEN 'Tajikistan' THEN 'TJ'
  WHEN 'Tanzania' THEN 'TZ'
  WHEN 'Thailand' THEN 'TH'
  WHEN 'Timor-Leste' THEN 'TL'
  WHEN 'Togo' THEN 'TG'
  WHEN 'Tonga' THEN 'TO'
  WHEN 'Trinidad and Tobago' THEN 'TT'
  WHEN 'Tunisia' THEN 'TN'
  WHEN 'Turkey' THEN 'TR'
  WHEN 'Turkmenistan' THEN 'TM'
  WHEN 'Tuvalu' THEN 'TV'
  WHEN 'Uganda' THEN 'UG'
  WHEN 'Ukraine' THEN 'UA'
  WHEN 'United Arab Emirates' THEN 'AE'
  WHEN 'Uruguay' THEN 'UY'
  WHEN 'Uzbekistan' THEN 'UZ'
  WHEN 'Vanuatu' THEN 'VU'
  WHEN 'Vatican City' THEN 'VA'
  WHEN 'Venezuela' THEN 'VE'
  WHEN 'Vietnam' THEN 'VN'
  WHEN 'Yemen' THEN 'YE'
  WHEN 'Zambia' THEN 'ZM'
  WHEN 'Zimbabwe' THEN 'ZW'
  ELSE current_country -- Keep as is if no match (might already be a code or unknown country)
END
WHERE current_country IS NOT NULL;

-- Update tenant_references employment_company_country field
UPDATE tenant_references
SET employment_company_country = CASE employment_company_country
  WHEN 'United Kingdom' THEN 'GB'
  WHEN 'United States' THEN 'US'
  WHEN 'Ireland' THEN 'IE'
  WHEN 'Canada' THEN 'CA'
  WHEN 'Australia' THEN 'AU'
  WHEN 'Germany' THEN 'DE'
  WHEN 'France' THEN 'FR'
  WHEN 'Spain' THEN 'ES'
  WHEN 'Italy' THEN 'IT'
  WHEN 'Netherlands' THEN 'NL'
  WHEN 'Belgium' THEN 'BE'
  WHEN 'Switzerland' THEN 'CH'
  WHEN 'Austria' THEN 'AT'
  WHEN 'Sweden' THEN 'SE'
  WHEN 'Norway' THEN 'NO'
  WHEN 'Denmark' THEN 'DK'
  WHEN 'Finland' THEN 'FI'
  WHEN 'Poland' THEN 'PL'
  WHEN 'India' THEN 'IN'
  WHEN 'China' THEN 'CN'
  WHEN 'Japan' THEN 'JP'
  WHEN 'Singapore' THEN 'SG'
  WHEN 'South Korea' THEN 'KR'
  WHEN 'Brazil' THEN 'BR'
  WHEN 'Mexico' THEN 'MX'
  WHEN 'Argentina' THEN 'AR'
  WHEN 'South Africa' THEN 'ZA'
  WHEN 'New Zealand' THEN 'NZ'
  WHEN 'Afghanistan' THEN 'AF'
  WHEN 'Albania' THEN 'AL'
  WHEN 'Algeria' THEN 'DZ'
  WHEN 'Andorra' THEN 'AD'
  WHEN 'Angola' THEN 'AO'
  WHEN 'Armenia' THEN 'AM'
  WHEN 'Azerbaijan' THEN 'AZ'
  WHEN 'Bahrain' THEN 'BH'
  WHEN 'Bangladesh' THEN 'BD'
  WHEN 'Belarus' THEN 'BY'
  WHEN 'Belize' THEN 'BZ'
  WHEN 'Benin' THEN 'BJ'
  WHEN 'Bhutan' THEN 'BT'
  WHEN 'Bolivia' THEN 'BO'
  WHEN 'Bosnia and Herzegovina' THEN 'BA'
  WHEN 'Botswana' THEN 'BW'
  WHEN 'Brunei' THEN 'BN'
  WHEN 'Bulgaria' THEN 'BG'
  WHEN 'Burkina Faso' THEN 'BF'
  WHEN 'Burundi' THEN 'BI'
  WHEN 'Cambodia' THEN 'KH'
  WHEN 'Cameroon' THEN 'CM'
  WHEN 'Cape Verde' THEN 'CV'
  WHEN 'Central African Republic' THEN 'CF'
  WHEN 'Chad' THEN 'TD'
  WHEN 'Chile' THEN 'CL'
  WHEN 'Colombia' THEN 'CO'
  WHEN 'Comoros' THEN 'KM'
  WHEN 'Congo' THEN 'CG'
  WHEN 'Costa Rica' THEN 'CR'
  WHEN 'Croatia' THEN 'HR'
  WHEN 'Cuba' THEN 'CU'
  WHEN 'Cyprus' THEN 'CY'
  WHEN 'Czech Republic' THEN 'CZ'
  WHEN 'Djibouti' THEN 'DJ'
  WHEN 'Dominican Republic' THEN 'DO'
  WHEN 'Ecuador' THEN 'EC'
  WHEN 'Egypt' THEN 'EG'
  WHEN 'El Salvador' THEN 'SV'
  WHEN 'Equatorial Guinea' THEN 'GQ'
  WHEN 'Eritrea' THEN 'ER'
  WHEN 'Estonia' THEN 'EE'
  WHEN 'Ethiopia' THEN 'ET'
  WHEN 'Fiji' THEN 'FJ'
  WHEN 'Gabon' THEN 'GA'
  WHEN 'Gambia' THEN 'GM'
  WHEN 'Georgia' THEN 'GE'
  WHEN 'Ghana' THEN 'GH'
  WHEN 'Greece' THEN 'GR'
  WHEN 'Guatemala' THEN 'GT'
  WHEN 'Guinea' THEN 'GN'
  WHEN 'Guinea-Bissau' THEN 'GW'
  WHEN 'Guyana' THEN 'GY'
  WHEN 'Haiti' THEN 'HT'
  WHEN 'Honduras' THEN 'HN'
  WHEN 'Hungary' THEN 'HU'
  WHEN 'Iceland' THEN 'IS'
  WHEN 'Indonesia' THEN 'ID'
  WHEN 'Iran' THEN 'IR'
  WHEN 'Iraq' THEN 'IQ'
  WHEN 'Israel' THEN 'IL'
  WHEN 'Jamaica' THEN 'JM'
  WHEN 'Jordan' THEN 'JO'
  WHEN 'Kazakhstan' THEN 'KZ'
  WHEN 'Kenya' THEN 'KE'
  WHEN 'Kiribati' THEN 'KI'
  WHEN 'Kuwait' THEN 'KW'
  WHEN 'Kyrgyzstan' THEN 'KG'
  WHEN 'Laos' THEN 'LA'
  WHEN 'Latvia' THEN 'LV'
  WHEN 'Lebanon' THEN 'LB'
  WHEN 'Lesotho' THEN 'LS'
  WHEN 'Liberia' THEN 'LR'
  WHEN 'Libya' THEN 'LY'
  WHEN 'Liechtenstein' THEN 'LI'
  WHEN 'Lithuania' THEN 'LT'
  WHEN 'Luxembourg' THEN 'LU'
  WHEN 'Macedonia' THEN 'MK'
  WHEN 'Madagascar' THEN 'MG'
  WHEN 'Malawi' THEN 'MW'
  WHEN 'Malaysia' THEN 'MY'
  WHEN 'Maldives' THEN 'MV'
  WHEN 'Mali' THEN 'ML'
  WHEN 'Malta' THEN 'MT'
  WHEN 'Marshall Islands' THEN 'MH'
  WHEN 'Mauritania' THEN 'MR'
  WHEN 'Mauritius' THEN 'MU'
  WHEN 'Micronesia' THEN 'FM'
  WHEN 'Moldova' THEN 'MD'
  WHEN 'Monaco' THEN 'MC'
  WHEN 'Mongolia' THEN 'MN'
  WHEN 'Montenegro' THEN 'ME'
  WHEN 'Morocco' THEN 'MA'
  WHEN 'Mozambique' THEN 'MZ'
  WHEN 'Myanmar' THEN 'MM'
  WHEN 'Namibia' THEN 'NA'
  WHEN 'Nauru' THEN 'NR'
  WHEN 'Nepal' THEN 'NP'
  WHEN 'Nicaragua' THEN 'NI'
  WHEN 'Niger' THEN 'NE'
  WHEN 'Nigeria' THEN 'NG'
  WHEN 'North Korea' THEN 'KP'
  WHEN 'Oman' THEN 'OM'
  WHEN 'Pakistan' THEN 'PK'
  WHEN 'Palau' THEN 'PW'
  WHEN 'Panama' THEN 'PA'
  WHEN 'Papua New Guinea' THEN 'PG'
  WHEN 'Paraguay' THEN 'PY'
  WHEN 'Peru' THEN 'PE'
  WHEN 'Philippines' THEN 'PH'
  WHEN 'Portugal' THEN 'PT'
  WHEN 'Qatar' THEN 'QA'
  WHEN 'Romania' THEN 'RO'
  WHEN 'Russia' THEN 'RU'
  WHEN 'Rwanda' THEN 'RW'
  WHEN 'Saint Kitts and Nevis' THEN 'KN'
  WHEN 'Saint Lucia' THEN 'LC'
  WHEN 'Saint Vincent and the Grenadines' THEN 'VC'
  WHEN 'Samoa' THEN 'WS'
  WHEN 'San Marino' THEN 'SM'
  WHEN 'Sao Tome and Principe' THEN 'ST'
  WHEN 'Saudi Arabia' THEN 'SA'
  WHEN 'Senegal' THEN 'SN'
  WHEN 'Serbia' THEN 'RS'
  WHEN 'Seychelles' THEN 'SC'
  WHEN 'Sierra Leone' THEN 'SL'
  WHEN 'Slovakia' THEN 'SK'
  WHEN 'Slovenia' THEN 'SI'
  WHEN 'Solomon Islands' THEN 'SB'
  WHEN 'Somalia' THEN 'SO'
  WHEN 'South Sudan' THEN 'SS'
  WHEN 'Sri Lanka' THEN 'LK'
  WHEN 'Sudan' THEN 'SD'
  WHEN 'Suriname' THEN 'SR'
  WHEN 'Swaziland' THEN 'SZ'
  WHEN 'Syria' THEN 'SY'
  WHEN 'Tajikistan' THEN 'TJ'
  WHEN 'Tanzania' THEN 'TZ'
  WHEN 'Thailand' THEN 'TH'
  WHEN 'Timor-Leste' THEN 'TL'
  WHEN 'Togo' THEN 'TG'
  WHEN 'Tonga' THEN 'TO'
  WHEN 'Trinidad and Tobago' THEN 'TT'
  WHEN 'Tunisia' THEN 'TN'
  WHEN 'Turkey' THEN 'TR'
  WHEN 'Turkmenistan' THEN 'TM'
  WHEN 'Tuvalu' THEN 'TV'
  WHEN 'Uganda' THEN 'UG'
  WHEN 'Ukraine' THEN 'UA'
  WHEN 'United Arab Emirates' THEN 'AE'
  WHEN 'Uruguay' THEN 'UY'
  WHEN 'Uzbekistan' THEN 'UZ'
  WHEN 'Vanuatu' THEN 'VU'
  WHEN 'Vatican City' THEN 'VA'
  WHEN 'Venezuela' THEN 'VE'
  WHEN 'Vietnam' THEN 'VN'
  WHEN 'Yemen' THEN 'YE'
  WHEN 'Zambia' THEN 'ZM'
  WHEN 'Zimbabwe' THEN 'ZW'
  ELSE employment_company_country
END
WHERE employment_company_country IS NOT NULL;

-- Update tenant_references previous_rental_country field (if it exists)
UPDATE tenant_references
SET previous_rental_country = CASE previous_rental_country
  WHEN 'United Kingdom' THEN 'GB'
  WHEN 'United States' THEN 'US'
  WHEN 'Ireland' THEN 'IE'
  WHEN 'Canada' THEN 'CA'
  WHEN 'Australia' THEN 'AU'
  WHEN 'Germany' THEN 'DE'
  WHEN 'France' THEN 'FR'
  WHEN 'Spain' THEN 'ES'
  WHEN 'Italy' THEN 'IT'
  WHEN 'Netherlands' THEN 'NL'
  WHEN 'Belgium' THEN 'BE'
  WHEN 'Switzerland' THEN 'CH'
  WHEN 'Austria' THEN 'AT'
  WHEN 'Sweden' THEN 'SE'
  WHEN 'Norway' THEN 'NO'
  WHEN 'Denmark' THEN 'DK'
  WHEN 'Finland' THEN 'FI'
  WHEN 'Poland' THEN 'PL'
  WHEN 'India' THEN 'IN'
  WHEN 'China' THEN 'CN'
  WHEN 'Japan' THEN 'JP'
  WHEN 'Singapore' THEN 'SG'
  WHEN 'South Korea' THEN 'KR'
  WHEN 'Brazil' THEN 'BR'
  WHEN 'Mexico' THEN 'MX'
  WHEN 'Argentina' THEN 'AR'
  WHEN 'South Africa' THEN 'ZA'
  WHEN 'New Zealand' THEN 'NZ'
  WHEN 'Afghanistan' THEN 'AF'
  WHEN 'Albania' THEN 'AL'
  WHEN 'Algeria' THEN 'DZ'
  WHEN 'Andorra' THEN 'AD'
  WHEN 'Angola' THEN 'AO'
  WHEN 'Armenia' THEN 'AM'
  WHEN 'Azerbaijan' THEN 'AZ'
  WHEN 'Bahrain' THEN 'BH'
  WHEN 'Bangladesh' THEN 'BD'
  WHEN 'Belarus' THEN 'BY'
  WHEN 'Belize' THEN 'BZ'
  WHEN 'Benin' THEN 'BJ'
  WHEN 'Bhutan' THEN 'BT'
  WHEN 'Bolivia' THEN 'BO'
  WHEN 'Bosnia and Herzegovina' THEN 'BA'
  WHEN 'Botswana' THEN 'BW'
  WHEN 'Brunei' THEN 'BN'
  WHEN 'Bulgaria' THEN 'BG'
  WHEN 'Burkina Faso' THEN 'BF'
  WHEN 'Burundi' THEN 'BI'
  WHEN 'Cambodia' THEN 'KH'
  WHEN 'Cameroon' THEN 'CM'
  WHEN 'Cape Verde' THEN 'CV'
  WHEN 'Central African Republic' THEN 'CF'
  WHEN 'Chad' THEN 'TD'
  WHEN 'Chile' THEN 'CL'
  WHEN 'Colombia' THEN 'CO'
  WHEN 'Comoros' THEN 'KM'
  WHEN 'Congo' THEN 'CG'
  WHEN 'Costa Rica' THEN 'CR'
  WHEN 'Croatia' THEN 'HR'
  WHEN 'Cuba' THEN 'CU'
  WHEN 'Cyprus' THEN 'CY'
  WHEN 'Czech Republic' THEN 'CZ'
  WHEN 'Djibouti' THEN 'DJ'
  WHEN 'Dominican Republic' THEN 'DO'
  WHEN 'Ecuador' THEN 'EC'
  WHEN 'Egypt' THEN 'EG'
  WHEN 'El Salvador' THEN 'SV'
  WHEN 'Equatorial Guinea' THEN 'GQ'
  WHEN 'Eritrea' THEN 'ER'
  WHEN 'Estonia' THEN 'EE'
  WHEN 'Ethiopia' THEN 'ET'
  WHEN 'Fiji' THEN 'FJ'
  WHEN 'Gabon' THEN 'GA'
  WHEN 'Gambia' THEN 'GM'
  WHEN 'Georgia' THEN 'GE'
  WHEN 'Ghana' THEN 'GH'
  WHEN 'Greece' THEN 'GR'
  WHEN 'Guatemala' THEN 'GT'
  WHEN 'Guinea' THEN 'GN'
  WHEN 'Guinea-Bissau' THEN 'GW'
  WHEN 'Guyana' THEN 'GY'
  WHEN 'Haiti' THEN 'HT'
  WHEN 'Honduras' THEN 'HN'
  WHEN 'Hungary' THEN 'HU'
  WHEN 'Iceland' THEN 'IS'
  WHEN 'Indonesia' THEN 'ID'
  WHEN 'Iran' THEN 'IR'
  WHEN 'Iraq' THEN 'IQ'
  WHEN 'Israel' THEN 'IL'
  WHEN 'Jamaica' THEN 'JM'
  WHEN 'Jordan' THEN 'JO'
  WHEN 'Kazakhstan' THEN 'KZ'
  WHEN 'Kenya' THEN 'KE'
  WHEN 'Kiribati' THEN 'KI'
  WHEN 'Kuwait' THEN 'KW'
  WHEN 'Kyrgyzstan' THEN 'KG'
  WHEN 'Laos' THEN 'LA'
  WHEN 'Latvia' THEN 'LV'
  WHEN 'Lebanon' THEN 'LB'
  WHEN 'Lesotho' THEN 'LS'
  WHEN 'Liberia' THEN 'LR'
  WHEN 'Libya' THEN 'LY'
  WHEN 'Liechtenstein' THEN 'LI'
  WHEN 'Lithuania' THEN 'LT'
  WHEN 'Luxembourg' THEN 'LU'
  WHEN 'Macedonia' THEN 'MK'
  WHEN 'Madagascar' THEN 'MG'
  WHEN 'Malawi' THEN 'MW'
  WHEN 'Malaysia' THEN 'MY'
  WHEN 'Maldives' THEN 'MV'
  WHEN 'Mali' THEN 'ML'
  WHEN 'Malta' THEN 'MT'
  WHEN 'Marshall Islands' THEN 'MH'
  WHEN 'Mauritania' THEN 'MR'
  WHEN 'Mauritius' THEN 'MU'
  WHEN 'Micronesia' THEN 'FM'
  WHEN 'Moldova' THEN 'MD'
  WHEN 'Monaco' THEN 'MC'
  WHEN 'Mongolia' THEN 'MN'
  WHEN 'Montenegro' THEN 'ME'
  WHEN 'Morocco' THEN 'MA'
  WHEN 'Mozambique' THEN 'MZ'
  WHEN 'Myanmar' THEN 'MM'
  WHEN 'Namibia' THEN 'NA'
  WHEN 'Nauru' THEN 'NR'
  WHEN 'Nepal' THEN 'NP'
  WHEN 'Nicaragua' THEN 'NI'
  WHEN 'Niger' THEN 'NE'
  WHEN 'Nigeria' THEN 'NG'
  WHEN 'North Korea' THEN 'KP'
  WHEN 'Oman' THEN 'OM'
  WHEN 'Pakistan' THEN 'PK'
  WHEN 'Palau' THEN 'PW'
  WHEN 'Panama' THEN 'PA'
  WHEN 'Papua New Guinea' THEN 'PG'
  WHEN 'Paraguay' THEN 'PY'
  WHEN 'Peru' THEN 'PE'
  WHEN 'Philippines' THEN 'PH'
  WHEN 'Portugal' THEN 'PT'
  WHEN 'Qatar' THEN 'QA'
  WHEN 'Romania' THEN 'RO'
  WHEN 'Russia' THEN 'RU'
  WHEN 'Rwanda' THEN 'RW'
  WHEN 'Saint Kitts and Nevis' THEN 'KN'
  WHEN 'Saint Lucia' THEN 'LC'
  WHEN 'Saint Vincent and the Grenadines' THEN 'VC'
  WHEN 'Samoa' THEN 'WS'
  WHEN 'San Marino' THEN 'SM'
  WHEN 'Sao Tome and Principe' THEN 'ST'
  WHEN 'Saudi Arabia' THEN 'SA'
  WHEN 'Senegal' THEN 'SN'
  WHEN 'Serbia' THEN 'RS'
  WHEN 'Seychelles' THEN 'SC'
  WHEN 'Sierra Leone' THEN 'SL'
  WHEN 'Slovakia' THEN 'SK'
  WHEN 'Slovenia' THEN 'SI'
  WHEN 'Solomon Islands' THEN 'SB'
  WHEN 'Somalia' THEN 'SO'
  WHEN 'South Sudan' THEN 'SS'
  WHEN 'Sri Lanka' THEN 'LK'
  WHEN 'Sudan' THEN 'SD'
  WHEN 'Suriname' THEN 'SR'
  WHEN 'Swaziland' THEN 'SZ'
  WHEN 'Syria' THEN 'SY'
  WHEN 'Tajikistan' THEN 'TJ'
  WHEN 'Tanzania' THEN 'TZ'
  WHEN 'Thailand' THEN 'TH'
  WHEN 'Timor-Leste' THEN 'TL'
  WHEN 'Togo' THEN 'TG'
  WHEN 'Tonga' THEN 'TO'
  WHEN 'Trinidad and Tobago' THEN 'TT'
  WHEN 'Tunisia' THEN 'TN'
  WHEN 'Turkey' THEN 'TR'
  WHEN 'Turkmenistan' THEN 'TM'
  WHEN 'Tuvalu' THEN 'TV'
  WHEN 'Uganda' THEN 'UG'
  WHEN 'Ukraine' THEN 'UA'
  WHEN 'United Arab Emirates' THEN 'AE'
  WHEN 'Uruguay' THEN 'UY'
  WHEN 'Uzbekistan' THEN 'UZ'
  WHEN 'Vanuatu' THEN 'VU'
  WHEN 'Vatican City' THEN 'VA'
  WHEN 'Venezuela' THEN 'VE'
  WHEN 'Vietnam' THEN 'VN'
  WHEN 'Yemen' THEN 'YE'
  WHEN 'Zambia' THEN 'ZM'
  WHEN 'Zimbabwe' THEN 'ZW'
  ELSE previous_rental_country
END
WHERE previous_rental_country IS NOT NULL;

-- Update tenant_reference_previous_addresses country field
UPDATE tenant_reference_previous_addresses
SET country = CASE country
  WHEN 'United Kingdom' THEN 'GB'
  WHEN 'United States' THEN 'US'
  WHEN 'Ireland' THEN 'IE'
  WHEN 'Canada' THEN 'CA'
  WHEN 'Australia' THEN 'AU'
  WHEN 'Germany' THEN 'DE'
  WHEN 'France' THEN 'FR'
  WHEN 'Spain' THEN 'ES'
  WHEN 'Italy' THEN 'IT'
  WHEN 'Netherlands' THEN 'NL'
  WHEN 'Belgium' THEN 'BE'
  WHEN 'Switzerland' THEN 'CH'
  WHEN 'Austria' THEN 'AT'
  WHEN 'Sweden' THEN 'SE'
  WHEN 'Norway' THEN 'NO'
  WHEN 'Denmark' THEN 'DK'
  WHEN 'Finland' THEN 'FI'
  WHEN 'Poland' THEN 'PL'
  WHEN 'India' THEN 'IN'
  WHEN 'China' THEN 'CN'
  WHEN 'Japan' THEN 'JP'
  WHEN 'Singapore' THEN 'SG'
  WHEN 'South Korea' THEN 'KR'
  WHEN 'Brazil' THEN 'BR'
  WHEN 'Mexico' THEN 'MX'
  WHEN 'Argentina' THEN 'AR'
  WHEN 'South Africa' THEN 'ZA'
  WHEN 'New Zealand' THEN 'NZ'
  WHEN 'Afghanistan' THEN 'AF'
  WHEN 'Albania' THEN 'AL'
  WHEN 'Algeria' THEN 'DZ'
  WHEN 'Andorra' THEN 'AD'
  WHEN 'Angola' THEN 'AO'
  WHEN 'Armenia' THEN 'AM'
  WHEN 'Azerbaijan' THEN 'AZ'
  WHEN 'Bahrain' THEN 'BH'
  WHEN 'Bangladesh' THEN 'BD'
  WHEN 'Belarus' THEN 'BY'
  WHEN 'Belize' THEN 'BZ'
  WHEN 'Benin' THEN 'BJ'
  WHEN 'Bhutan' THEN 'BT'
  WHEN 'Bolivia' THEN 'BO'
  WHEN 'Bosnia and Herzegovina' THEN 'BA'
  WHEN 'Botswana' THEN 'BW'
  WHEN 'Brunei' THEN 'BN'
  WHEN 'Bulgaria' THEN 'BG'
  WHEN 'Burkina Faso' THEN 'BF'
  WHEN 'Burundi' THEN 'BI'
  WHEN 'Cambodia' THEN 'KH'
  WHEN 'Cameroon' THEN 'CM'
  WHEN 'Cape Verde' THEN 'CV'
  WHEN 'Central African Republic' THEN 'CF'
  WHEN 'Chad' THEN 'TD'
  WHEN 'Chile' THEN 'CL'
  WHEN 'Colombia' THEN 'CO'
  WHEN 'Comoros' THEN 'KM'
  WHEN 'Congo' THEN 'CG'
  WHEN 'Costa Rica' THEN 'CR'
  WHEN 'Croatia' THEN 'HR'
  WHEN 'Cuba' THEN 'CU'
  WHEN 'Cyprus' THEN 'CY'
  WHEN 'Czech Republic' THEN 'CZ'
  WHEN 'Djibouti' THEN 'DJ'
  WHEN 'Dominican Republic' THEN 'DO'
  WHEN 'Ecuador' THEN 'EC'
  WHEN 'Egypt' THEN 'EG'
  WHEN 'El Salvador' THEN 'SV'
  WHEN 'Equatorial Guinea' THEN 'GQ'
  WHEN 'Eritrea' THEN 'ER'
  WHEN 'Estonia' THEN 'EE'
  WHEN 'Ethiopia' THEN 'ET'
  WHEN 'Fiji' THEN 'FJ'
  WHEN 'Gabon' THEN 'GA'
  WHEN 'Gambia' THEN 'GM'
  WHEN 'Georgia' THEN 'GE'
  WHEN 'Ghana' THEN 'GH'
  WHEN 'Greece' THEN 'GR'
  WHEN 'Guatemala' THEN 'GT'
  WHEN 'Guinea' THEN 'GN'
  WHEN 'Guinea-Bissau' THEN 'GW'
  WHEN 'Guyana' THEN 'GY'
  WHEN 'Haiti' THEN 'HT'
  WHEN 'Honduras' THEN 'HN'
  WHEN 'Hungary' THEN 'HU'
  WHEN 'Iceland' THEN 'IS'
  WHEN 'Indonesia' THEN 'ID'
  WHEN 'Iran' THEN 'IR'
  WHEN 'Iraq' THEN 'IQ'
  WHEN 'Israel' THEN 'IL'
  WHEN 'Jamaica' THEN 'JM'
  WHEN 'Jordan' THEN 'JO'
  WHEN 'Kazakhstan' THEN 'KZ'
  WHEN 'Kenya' THEN 'KE'
  WHEN 'Kiribati' THEN 'KI'
  WHEN 'Kuwait' THEN 'KW'
  WHEN 'Kyrgyzstan' THEN 'KG'
  WHEN 'Laos' THEN 'LA'
  WHEN 'Latvia' THEN 'LV'
  WHEN 'Lebanon' THEN 'LB'
  WHEN 'Lesotho' THEN 'LS'
  WHEN 'Liberia' THEN 'LR'
  WHEN 'Libya' THEN 'LY'
  WHEN 'Liechtenstein' THEN 'LI'
  WHEN 'Lithuania' THEN 'LT'
  WHEN 'Luxembourg' THEN 'LU'
  WHEN 'Macedonia' THEN 'MK'
  WHEN 'Madagascar' THEN 'MG'
  WHEN 'Malawi' THEN 'MW'
  WHEN 'Malaysia' THEN 'MY'
  WHEN 'Maldives' THEN 'MV'
  WHEN 'Mali' THEN 'ML'
  WHEN 'Malta' THEN 'MT'
  WHEN 'Marshall Islands' THEN 'MH'
  WHEN 'Mauritania' THEN 'MR'
  WHEN 'Mauritius' THEN 'MU'
  WHEN 'Micronesia' THEN 'FM'
  WHEN 'Moldova' THEN 'MD'
  WHEN 'Monaco' THEN 'MC'
  WHEN 'Mongolia' THEN 'MN'
  WHEN 'Montenegro' THEN 'ME'
  WHEN 'Morocco' THEN 'MA'
  WHEN 'Mozambique' THEN 'MZ'
  WHEN 'Myanmar' THEN 'MM'
  WHEN 'Namibia' THEN 'NA'
  WHEN 'Nauru' THEN 'NR'
  WHEN 'Nepal' THEN 'NP'
  WHEN 'Nicaragua' THEN 'NI'
  WHEN 'Niger' THEN 'NE'
  WHEN 'Nigeria' THEN 'NG'
  WHEN 'North Korea' THEN 'KP'
  WHEN 'Oman' THEN 'OM'
  WHEN 'Pakistan' THEN 'PK'
  WHEN 'Palau' THEN 'PW'
  WHEN 'Panama' THEN 'PA'
  WHEN 'Papua New Guinea' THEN 'PG'
  WHEN 'Paraguay' THEN 'PY'
  WHEN 'Peru' THEN 'PE'
  WHEN 'Philippines' THEN 'PH'
  WHEN 'Portugal' THEN 'PT'
  WHEN 'Qatar' THEN 'QA'
  WHEN 'Romania' THEN 'RO'
  WHEN 'Russia' THEN 'RU'
  WHEN 'Rwanda' THEN 'RW'
  WHEN 'Saint Kitts and Nevis' THEN 'KN'
  WHEN 'Saint Lucia' THEN 'LC'
  WHEN 'Saint Vincent and the Grenadines' THEN 'VC'
  WHEN 'Samoa' THEN 'WS'
  WHEN 'San Marino' THEN 'SM'
  WHEN 'Sao Tome and Principe' THEN 'ST'
  WHEN 'Saudi Arabia' THEN 'SA'
  WHEN 'Senegal' THEN 'SN'
  WHEN 'Serbia' THEN 'RS'
  WHEN 'Seychelles' THEN 'SC'
  WHEN 'Sierra Leone' THEN 'SL'
  WHEN 'Slovakia' THEN 'SK'
  WHEN 'Slovenia' THEN 'SI'
  WHEN 'Solomon Islands' THEN 'SB'
  WHEN 'Somalia' THEN 'SO'
  WHEN 'South Sudan' THEN 'SS'
  WHEN 'Sri Lanka' THEN 'LK'
  WHEN 'Sudan' THEN 'SD'
  WHEN 'Suriname' THEN 'SR'
  WHEN 'Swaziland' THEN 'SZ'
  WHEN 'Syria' THEN 'SY'
  WHEN 'Tajikistan' THEN 'TJ'
  WHEN 'Tanzania' THEN 'TZ'
  WHEN 'Thailand' THEN 'TH'
  WHEN 'Timor-Leste' THEN 'TL'
  WHEN 'Togo' THEN 'TG'
  WHEN 'Tonga' THEN 'TO'
  WHEN 'Trinidad and Tobago' THEN 'TT'
  WHEN 'Tunisia' THEN 'TN'
  WHEN 'Turkey' THEN 'TR'
  WHEN 'Turkmenistan' THEN 'TM'
  WHEN 'Tuvalu' THEN 'TV'
  WHEN 'Uganda' THEN 'UG'
  WHEN 'Ukraine' THEN 'UA'
  WHEN 'United Arab Emirates' THEN 'AE'
  WHEN 'Uruguay' THEN 'UY'
  WHEN 'Uzbekistan' THEN 'UZ'
  WHEN 'Vanuatu' THEN 'VU'
  WHEN 'Vatican City' THEN 'VA'
  WHEN 'Venezuela' THEN 'VE'
  WHEN 'Vietnam' THEN 'VN'
  WHEN 'Yemen' THEN 'YE'
  WHEN 'Zambia' THEN 'ZM'
  WHEN 'Zimbabwe' THEN 'ZW'
  ELSE country
END
WHERE country IS NOT NULL;
