-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.accountant_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_reference_id uuid NOT NULL,
  token text NOT NULL UNIQUE,
  accountant_firm_name text NOT NULL,
  accountant_contact_name text NOT NULL,
  accountant_email text NOT NULL,
  accountant_phone text,
  tenant_name text,
  business_name text,
  nature_of_business text,
  business_start_date date,
  annual_turnover numeric,
  annual_profit numeric,
  tax_returns_filed boolean,
  last_tax_return_date date,
  accounts_prepared boolean,
  accounts_year_end date,
  business_trading_status text,
  any_outstanding_tax_liabilities boolean,
  tax_liabilities_details text,
  business_financially_stable boolean,
  accountant_confirms_income boolean,
  estimated_monthly_income numeric,
  additional_comments text,
  would_recommend boolean,
  recommendation_comments text,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  signature_name text,
  signature text,
  date date,
  CONSTRAINT accountant_references_pkey PRIMARY KEY (id),
  CONSTRAINT accountant_references_tenant_reference_id_fkey FOREIGN KEY (tenant_reference_id) REFERENCES public.tenant_references(id)
);
CREATE TABLE public.agent_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_id uuid NOT NULL,
  agent_name text NOT NULL,
  agent_email text NOT NULL,
  agent_phone text NOT NULL,
  agency_name text,
  property_address text NOT NULL,
  property_city text,
  property_postcode text,
  tenancy_start_date date NOT NULL,
  tenancy_end_date date NOT NULL,
  monthly_rent numeric NOT NULL,
  rent_paid_on_time text NOT NULL,
  rent_paid_on_time_details text,
  property_condition text NOT NULL,
  property_condition_details text,
  neighbour_complaints text NOT NULL,
  neighbour_complaints_details text,
  breach_of_tenancy text NOT NULL,
  breach_of_tenancy_details text,
  would_rent_again text NOT NULL,
  would_rent_again_details text,
  additional_comments text,
  signature text NOT NULL,
  date date NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  signature_name text,
  property_address_line1 text,
  property_address_line2 text,
  CONSTRAINT agent_references_pkey PRIMARY KEY (id),
  CONSTRAINT agent_references_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.tenant_references(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  address text,
  city text,
  postcode text,
  phone text,
  website text,
  logo_url text,
  primary_color text DEFAULT '#A855F7'::text,
  button_color text DEFAULT '#A855F7'::text,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'member'::user_role,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_users_pkey PRIMARY KEY (id),
  CONSTRAINT company_users_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.employer_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_id uuid NOT NULL,
  company_name text NOT NULL,
  employer_name text NOT NULL,
  employer_position text NOT NULL,
  employer_email text NOT NULL,
  employer_phone text NOT NULL,
  employee_position text NOT NULL,
  employment_type text NOT NULL,
  employment_start_date date NOT NULL,
  employment_end_date date,
  is_current_employee boolean DEFAULT true,
  annual_salary numeric NOT NULL,
  salary_frequency text NOT NULL,
  is_probation text NOT NULL,
  probation_end_date date,
  employment_status text NOT NULL,
  performance_rating text NOT NULL,
  performance_details text,
  disciplinary_issues text NOT NULL,
  disciplinary_details text,
  absence_record text NOT NULL,
  absence_details text,
  would_reemploy text NOT NULL,
  would_reemploy_details text,
  additional_comments text,
  signature text NOT NULL,
  date date NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  signature_name text,
  CONSTRAINT employer_references_pkey PRIMARY KEY (id),
  CONSTRAINT employer_references_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.tenant_references(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  email text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'member'::user_role,
  token text NOT NULL UNIQUE,
  invited_by uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.landlord_references (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reference_id uuid NOT NULL,
  landlord_name text NOT NULL,
  landlord_email text NOT NULL,
  landlord_phone text NOT NULL,
  property_address text NOT NULL,
  tenancy_start_date date NOT NULL,
  tenancy_end_date date NOT NULL,
  monthly_rent numeric NOT NULL,
  rent_paid_on_time text NOT NULL,
  rent_paid_on_time_details text,
  property_condition text NOT NULL,
  property_condition_details text,
  neighbour_complaints text NOT NULL,
  neighbour_complaints_details text,
  breach_of_tenancy text NOT NULL,
  breach_of_tenancy_details text,
  would_rent_again text NOT NULL,
  would_rent_again_details text,
  additional_comments text,
  signature text NOT NULL,
  date date NOT NULL,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  signature_name text,
  property_city text,
  property_postcode text,
  property_address_line1 text,
  property_address_line2 text,
  CONSTRAINT landlord_references_pkey PRIMARY KEY (id),
  CONSTRAINT landlord_references_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.tenant_references(id)
);
CREATE TABLE public.reference_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reference_id uuid NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  file_type text,
  file_size integer,
  uploaded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reference_documents_pkey PRIMARY KEY (id),
  CONSTRAINT reference_documents_reference_id_fkey FOREIGN KEY (reference_id) REFERENCES public.tenant_references(id),
  CONSTRAINT reference_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.staff_users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT staff_users_pkey PRIMARY KEY (id),
  CONSTRAINT staff_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tenant_references (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  created_by uuid NOT NULL,
  tenant_first_name text NOT NULL,
  tenant_last_name text NOT NULL,
  tenant_email text NOT NULL,
  tenant_phone text,
  property_address text NOT NULL,
  property_city text,
  property_postcode text,
  monthly_rent numeric,
  move_in_date date,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::reference_status,
  reference_token text NOT NULL UNIQUE,
  token_expires_at timestamp with time zone NOT NULL,
  employment_status text,
  employer_name text,
  job_title text,
  annual_income numeric,
  employment_start_date date,
  previous_landlord_name text,
  previous_landlord_email text,
  previous_landlord_phone text,
  notes text,
  internal_notes text,
  submitted_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  employer_email text,
  employer_phone text,
  previous_street text,
  previous_city text,
  previous_postcode text,
  tenancy_years integer,
  tenancy_months integer,
  bank_statement_files ARRAY,
  payslip_files ARRAY,
  verified_by uuid,
  verified_at timestamp with time zone,
  verification_notes text,
  middle_name text,
  date_of_birth date,
  contact_number text,
  nationality text,
  id_document_type text,
  id_document_path text,
  selfie_path text,
  current_address_line1 text,
  current_address_line2 text,
  current_city text,
  current_postcode text,
  current_country text,
  proof_of_address_path text,
  income_regular_employment boolean DEFAULT false,
  income_benefits boolean DEFAULT false,
  income_savings_pension_investments boolean DEFAULT false,
  income_student boolean DEFAULT false,
  income_unemployed boolean DEFAULT false,
  employment_contract_type text,
  employment_is_hourly boolean DEFAULT false,
  employment_hours_per_month integer,
  employment_salary_amount numeric,
  employment_company_name text,
  employment_company_address_line1 text,
  employment_company_address_line2 text,
  employment_company_city text,
  employment_company_postcode text,
  employment_company_country text,
  employment_job_title text,
  employer_ref_position text,
  employer_ref_name text,
  employer_ref_email text,
  employer_ref_phone text,
  has_additional_income boolean DEFAULT false,
  additional_income_source text,
  additional_income_amount numeric,
  additional_income_frequency text,
  has_adverse_credit boolean DEFAULT false,
  adverse_credit_details text,
  is_smoker boolean,
  has_pets boolean DEFAULT false,
  pet_details text,
  marital_status text,
  number_of_dependants integer DEFAULT 0,
  dependants_details text,
  current_page integer DEFAULT 1,
  completed_pages ARRAY DEFAULT '{}'::integer[],
  previous_rental_address_line1 text,
  previous_rental_address_line2 text,
  previous_rental_city text,
  previous_rental_postcode text,
  previous_rental_country text,
  income_self_employed boolean DEFAULT false,
  self_employed_business_name text,
  self_employed_start_date date,
  self_employed_nature_of_business text,
  self_employed_annual_income numeric,
  accountant_name text,
  accountant_contact_name text,
  accountant_email text,
  accountant_phone text,
  reference_type text DEFAULT 'landlord'::text,
  term_years integer DEFAULT 0,
  term_months integer DEFAULT 0,
  parent_reference_id uuid,
  is_group_parent boolean DEFAULT false,
  rent_share numeric,
  tenant_position integer DEFAULT 1,
  CONSTRAINT tenant_references_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_references_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT tenant_references_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT tenant_references_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.staff_users(id),
  CONSTRAINT tenant_references_parent_reference_id_fkey FOREIGN KEY (parent_reference_id) REFERENCES public.tenant_references(id)
);
